### ISSUE TITLE
Control ECS Service level settings

### ISSUE THREAD

**Issue by ken9ross** [hamlet-io/engine-plugin-aws#123]
## Expected Behaviour
Record "opt-in"/"opt-out" status for an account by feature, allowing for AWS to remove or prevent status changes without causing a job failure

## Current Behaviour
None

## Possible Solution
Refer below

## Context
AWS sets "opt-in" and "opt-out" for feature deployments on a by account basis. We need the CMDB to capture this so that a feature can have the "opt-in"/"opt-out" status set by account in such a way that AWS removing the feature or disabling the ability to change the "opt-in"/"opt-out" status does not cause the job to fail, but does report a warning that the requested status is not found, or amendment is not allowed.

**Comment by roleyfoley** [comment]
@ken9ross What feature deployments are you looking for here? as far as I'm aware this is only available for the ECS AWS service. Is this what you meant? 

Also please note that I have removed the names of your customers ( hamlet doesn't need to know about that  as its an open source, public project )

**Comment by ken9ross** [comment]
At the moment the feature deployments listed are (under ECS/Account Settings):

- Amazon ECS ARN and resource ID settings (3 of)

But there are also two others in account settings:

- AWSVPC Trunking
- CloudWatch Container Insights

Which should probably be handled the same way if this is implemented as being able to set account settings through Hamlet. 

The specific flexibility I'm seeking is to handle the three "Amazon ECS ARN and resource ID settings" opt-in/opt-out as well as the next ones AWS implements through this same mechanism (the latter two being an afterthought)

**Comment by roleyfoley** [comment]
This has now been implemented in hamlet

**Comment by roleyfoley** [comment]
Testing has show a couple of things 
- You can't see what the effective values are if acount defaults have been set
- We shouldn't set the principal settings, instead lets remove them to enforce the use of the default settings
