### ISSUE TITLE
[BUG] ECS Processor profile failing to lookup maxcount

### ISSUE THREAD

**Issue by kshychko** [hamlet-io/engine-plugin-aws#280]
## Current Behaviour

When I'm trying to run a task using a solution file with no `MaxCount` attribute of processorProfile defined I'm getting the following error during blueprint generation:
21:43:52  ==> multiAZ  [in template "aws/components/ecs/state.ftl" at line 96, column 14]
## Expected Behaviour

A blueprint should be generated without error.
## Possible Solution

Freemarker `multiAZ` variable must be initialised before use:
https://github.com/hamlet-io/engine-plugin-aws/blob/master/aws/components/ecs/setup.ftl#L481
## Steps to Reproduce

1. Create a blueprint for a solution file, where ECS processor doesn't have MaxCount attribute specified.

## Your Environment
* CMDB Version used: v1.3.2
* Blueprint:  fail to generate

**Comment by roleyfoley** [comment]
Fixed and confirmed working
